### PR TITLE
Do not build if lsb_release is not installed.

### LINKED ISSUE #77: Build script fails in non obvious way if  lsb_release is not installed when building on debian
The line i see buried in the build script output is
```
./build.sh: 90: ./build.sh: lsb_release: not found
```
followed by error spew from the python installer

### PR DESCRIPTION
**Pull request by snim2**
This is not needed by the bin/ scripts, but the build script uses it to determine the Debian version (in order to pass correct CLI arguments to pip).

Fixes #77

### CODE REVIEW

File: build.sh [hunk 1]
```diff
@@ -70,6 +70,12 @@ if [ $? != 0 ]; then
     exit 1
 fi
 
+which lsb_release > /dev/null 2>&1
```
Comment (ltratt) [inline build.sh]: I don't think we can do this: `lsb_release` is, I belive, a Linux-only thing (and maybe not even an every-Linux thing?). That means this commit would stop us running on non-Linu. What do we use `lsb_release` for? Can we find an alternative?

Comment (snim2) [reply build.sh]: We use it in the build script to determine how to install the Python libraries, this is the relevant code:

```sh
# Install rpy2 Python package.
DEB8_HACK="0"
if [ "$(lsb_release -si)" = "Debian" ]; then
    DEB_MAJOR_V=`lsb_release -sr | cut -c1`
    if [ "${DEB_MAJOR_V}" = "8" ] || [ "${DEB_MAJOR_V}" = "9" ]; then
        DEB8_HACK="1"
    fi
fi

if [ "${DEB8_HACK}" = "1" ]; then
    # Debian 8 or 9
    pip install --system --target "${PIP_TARGET_DIR}" "rpy2==2.8.5"
else
    pip install --target "${PIP_TARGET_DIR}" "rpy2==2.8.5"
fi
```

Comment (ltratt) [reply build.sh]: We need something which isn't Linux specific-- we know people are using this on OS X, for example. At the very least, we would need to gate this i.e. say "if running on Debian, try this branch".

Comment (snim2) [reply build.sh]: I'm hoping the next commit has helped?

**Comment by ltratt** [comment]
Do we know for sure that every Linux has `lsb_release`. @ptersilie does Arch have this command?

**Comment by fsfod** [comment]
@snim2 So it seems to be not working correctly, the bash script is exiting from a non zero error code that 'which' returned it looks like

**Comment by snim2** [comment]
Hrm, on which machine / OS?

**Comment by fsfod** [comment]
Its running under Debian 9\Stretch that is running in WSL\Windows Subsystem for Linux

**Comment by snim2** [comment]
So, it runs fine on bencher8 which is Debian 9.4. Can you please run the build script with `set -x` somewhere near the start of the script, and paste the output here?

**Comment by fsfod** [comment]
I suspect people running this in docker might suffer from a missing lsb_release as well.

**Comment by fsfod** [comment]
Heres the output
```
+ pwd
+ R_LIB_DIR=/home/fsfod/warmup_stats/work/rlibs
+ pwd
+ PIP_TARGET_DIR=/home/fsfod/warmup_stats/work/pylibs
+ which git
+ [ 0 != 0 ]
+ which python2.7
+ [ 0 != 0 ]
+ python2.7 -c import setuptools
+ [ 0 != 0 ]
+ which R
+ [ 0 != 0 ]
+ uname -o
+ OS_NAME=GNU/Linux
+ [ GNU/Linux = Linux ]
+ [ GNU/Linux = GNU/Linux ]
+ which lsb_release
```

**Comment by fsfod** [comment]
and my shell ~/warmup_stats$ $SHELL --version
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)

**Comment by snim2** [comment]
What happens if you run `which lsb_release` just from your shell?

**Comment by fsfod** [comment]
It printed nothing when i tried it earlier

File: build.sh [hunk 2]
```diff
@@ -85,12 +94,14 @@ echo "install.packages('devtools', lib='${R_LIB_DIR}', repos='http://cran.us.r-p
 echo "install.packages('MultinomialCI', lib='${R_LIB_DIR}', repos='http://cran.us.r-project.org')" | R_LIBS_USER=${R_LIB_DIR} R --no-save
 echo "devtools::install_git('git://github.com/rkillick/changepoint', branch = 'master')" | R_LIBS_USER=${R_LIB_DIR} R --no-save
 
-# Install rpy2 Python package.
-DEB8_HACK="0"
-if [ "$(lsb_release -si)" = "Debian" ]; then
-    DEB_MAJOR_V=`lsb_release -sr | cut -c1`
-    if [ "${DEB_MAJOR_V}" = "8" ] || [ "${DEB_MAJOR_V}" = "9" ]; then
-        DEB8_HACK="1"
+if [ "${OS_NAME}" = "Linux" ] ||[ "${OS_NAME}" = "GNU/Linux" ]; then
```
[the remark this answers is not in the document]
Comment (fsfod) [reply build.sh]: Maybe this is too much shell magic but this version of the check works for me 
```
command -v lsb_release >/dev/null 2>&1 || { echo >&2 "lsb_release must be installed"; exit 1; }
````

**Comment by snim2** [comment]
OK, the last commit works on my laptop and bencher8

File: build.sh (hunk 2 above)
[the remark this answers is not in the document]
Comment (ltratt) [reply build.sh]: Can you try the new version and see if it works for you? I doubt we need such magic, but I might be wrong.

**Comment by fsfod** [comment]
It still exiting after calling 'which'. I think we should use something like 'type' or 'command -v'

**Comment by snim2** [comment]
OK, how about this?

**Comment by snim2** [comment]
OK, I think this is me being daft, I'll push a fix in a minute

**Comment by snim2** [comment]
OK, try that one

**Comment by fsfod** [comment]
Well i did get burned by not using set -e in my own install script for the Lua stuff

**Comment by ltratt** [comment]
@snim2 Good point. Then you'll have to attach this to every line that can fail `|| exit $?`. It's a bit ugly, but it works (I've done it more than once).

**Comment by snim2** [comment]
Just to be pedantically clear, you mean remove `set -e` and add `|| exit $?` to many lines?

**Comment by ltratt** [comment]
I can't think of another safe solution :/ Annoyingly, `which` outputs both success and error messages on `stdout`; and `whereis` is hugely different on Linux and BSD, and hard to use portably...

**Comment by snim2** [comment]
OK, I'm not sure whether I have been too conservative or the opposite in the last commit, but I think it's roughly what you're after.

File: build.sh [hunk 3]
```diff
@@ -40,8 +40,8 @@
 # Build dependencies for scripts in bin/
 
 # Local directories for installing Python and R packages.
-R_LIB_DIR=`pwd`/work/rlibs
-PIP_TARGET_DIR=`pwd`/work/pylibs
+R_LIB_DIR=`pwd`/work/rlibs || exit $?
```
Comment (ltratt) [inline build.sh]: These lines can't fail in a meaningful way, so no need to add ``|| exit $? here.

File: build.sh [hunk 4]
```diff
@@ -69,7 +69,7 @@ if [ $? != 0 ]; then
 fi
 
 version() {
-    echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }';
+    echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }' || exit $?;
```
Comment (ltratt) [inline build.sh]: Or here.

File: build.sh [hunk 5]
```diff
@@ -78,19 +78,19 @@ if [ $(($(version "$(R --version | awk 'NR==1 {print $3}')") <= $(version "3.3.1
...
-echo "install.packages('MultinomialCI', lib='${R_LIB_DIR}', repos='http://cran.us.r-project.org')" | R_LIBS_USER=${R_LIB_DIR} R --no-save
-echo "devtools::install_git('git://github.com/rkillick/changepoint', branch = 'master')" | R_LIBS_USER=${R_LIB_DIR} R --no-save
+mkdir -p ${R_LIB_DIR} || exit $?
+echo "install.packages('devtools', lib='${R_LIB_DIR}', repos='http://cran.us.r-project.org')" | R_LIBS_USER=${R_LIB_DIR} R --no-save || exit $?
+echo "install.packages('MultinomialCI', lib='${R_LIB_DIR}', repos='http://cran.us.r-project.org')" | R_LIBS_USER=${R_LIB_DIR} R --no-save || exit $?
+echo "devtools::install_git('git://github.com/rkillick/changepoint', branch = 'master')" | R_LIBS_USER=${R_LIB_DIR} R --no-save || exit $?
 
 # Install the rpy2 Python package.
-which lsb_release > /dev/null 2>&1
+which lsb_release > /dev/null 2>&1 || exit $?
```
Comment (ltratt) [inline build.sh]: And has to be remove here (otherwise it'll fail on systems where `lsb_release` doesn't exist, negating the test.

**Comment by snim2** [comment]
OK to squash?

**Comment by ltratt** [comment]
Has it been tested on successfully on your laptop, b8, and Tom's machine?

**Comment by snim2** [comment]
It works fine on my laptop and b8

**Comment by ltratt** [comment]
@fsfod does it work for you?

**Comment by fsfod** [comment]
Yes it installed and generated a pdf without any issues

**Comment by ltratt** [comment]
OK, please squash.

**Comment by snim2** [comment]
Squashed
